version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    build: ../frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  postgres_data:
